# Generated by Django 5.2.15 on 2026-07-02 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=1)),
                ('is_phishing', models.IntegerField(default=0)),
                ('question', models.TextField(blank=True, default='')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('picture', models.BinaryField()),
                ('picture_height', models.IntegerField(default=0)),
                ('picture_width', models.IntegerField(default=0)),
                ('created', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('x', models.CharField(blank=True, default='', max_length=32)),
                ('y', models.CharField(blank=True, default='', max_length=32)),
                ('w', models.CharField(blank=True, max_length=32, null=True)),
                ('h', models.CharField(blank=True, max_length=32, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='phishing_test.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField(blank=True, default='')),
                ('answer_status', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='phishing_test.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_text', models.TextField(blank=True, default='')),
                ('is_phishing', models.IntegerField()),
                ('answer_status', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='users.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'question_id'), name='unique_student_question_answer')],
            },
        ),
        migrations.CreateModel(
            name='AnswerSelectedOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('option_id', models.IntegerField()),
                ('option_text', models.TextField(blank=True, default='')),
                ('right_answer', models.IntegerField(blank=True, null=True)),
                ('is_selected', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='users.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'question_id', 'option_id'), name='unique_student_question_option')],
            },
        ),
    ]
