# Generated by Django 5.2.15 on 2026-07-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phishing_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_phishing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
